### ISSUE TITLE
not really an issue but ...

### ISSUE THREAD

**Issue by 5chufti** [elektra42/freifunk-open-mppt#2]
it would be nice to have some explanation about the function around PB1 - R/C filter/integrator - U2 - R11..R15/D4 - Vsense. I looked at the "homepage", found good explanation about mppt, but none about theory behind "feedback/control" circuitry.

**Comment by elektra42** [comment]
The R/C filter network provides a stable and low noise reference voltage for the V+ input of the OP-Amp, which is controlled by the PWM output of the µC. Since the OP-Amp has no symmetrical power supply, a bit of trickery at the voltage divider is necessary to put the PWM signal of the µC, which can not exceed 3.3 V, to a level that is high enough about GND to be compared by the V- input of the OP-Amp, which is connected to the solar input rail via a voltage divider. If the V+ input is greater than the V- input of the OP-Amp, the input solar voltage is lower than the set MPP point. The output of the OP-Amp goes up, signalling the DC/DC buck controller chip MC33063 via its reference pin that the set output voltage has been exceeded. In response, the MC33063 will reduce the pulse-pause-ratio of the PWM in the MC33063, hence the current load on the solar module will go down and the solar input voltage rises to the point where V- at the Op-amp becomes greater then V+. V out of the OP-Amp goes down: So here we have a control loop, controlling the MPP voltage.

By controlling the PWM output of the µC, the MPP input voltage can be controlled by the µC firmware.

**Comment by 5chufti** [comment]
thank you for the quick answer.
